# Generated by Django 4.2.9 on 2026-01-14 23:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('email', models.EmailField(error_messages={'unique': 'Un utilisateur avec cette adresse email existe déjà.'}, max_length=254, unique=True, verbose_name='adresse email')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='prénom')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='nom')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='téléphone')),
                ('company_name', models.CharField(blank=True, max_length=200, verbose_name="nom de l'entreprise")),
                ('email_notifications', models.BooleanField(default=True, help_text="Recevoir les notifications de fin d'audit par email", verbose_name='notifications par email')),
                ('preferred_language', models.CharField(choices=[('fr', 'Français'), ('en', 'English'), ('de', 'Deutsch'), ('es', 'Español'), ('it', 'Italiano')], default='fr', max_length=5, verbose_name='langue préférée')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name="date d'inscription")),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='dernière connexion')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'utilisateur',
                'verbose_name_plural': 'utilisateurs',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amazon_seller_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ID vendeur Amazon')),
                ('amazon_marketplace_ids', models.JSONField(blank=True, default=list, help_text='Liste des IDs de marketplace connectés', verbose_name='marketplaces Amazon')),
                ('amazon_connected_at', models.DateTimeField(blank=True, null=True, verbose_name='date de connexion Amazon')),
                ('amazon_token_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expiration du token Amazon')),
                ('subscription_tier', models.CharField(choices=[('free', 'Gratuit'), ('starter', 'Starter'), ('pro', 'Professionnel'), ('enterprise', 'Entreprise')], default='free', max_length=20, verbose_name="niveau d'abonnement")),
                ('subscription_started_at', models.DateTimeField(blank=True, null=True, verbose_name="début de l'abonnement")),
                ('subscription_ends_at', models.DateTimeField(blank=True, null=True, verbose_name="fin de l'abonnement")),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID client Stripe')),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID abonnement Stripe')),
                ('credits_balance', models.IntegerField(default=0, help_text='Crédits disponibles pour télécharger des dossiers', verbose_name='solde de crédits')),
                ('total_audits_run', models.IntegerField(default=0, verbose_name="nombre total d'audits")),
                ('total_claims_generated', models.IntegerField(default=0, verbose_name='nombre total de réclamations')),
                ('total_estimated_recovery', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='montant total estimé récupérable')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'profil vendeur',
                'verbose_name_plural': 'profils vendeurs',
            },
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='adresse IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('login_successful', models.BooleanField(default=True, verbose_name='connexion réussie')),
                ('login_at', models.DateTimeField(auto_now_add=True, verbose_name='date de connexion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'historique de connexion',
                'verbose_name_plural': 'historiques de connexion',
                'ordering': ['-login_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='montant')),
                ('transaction_type', models.CharField(choices=[('credit', 'Crédit'), ('debit', 'Débit'), ('refund', 'Remboursement'), ('bonus', 'Bonus')], max_length=20, verbose_name='type de transaction')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='référence')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('seller_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to='accounts.sellerprofile', verbose_name='profil vendeur')),
            ],
            options={
                'verbose_name': 'transaction de crédits',
                'verbose_name_plural': 'transactions de crédits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('key_prefix', models.CharField(max_length=8, verbose_name='préfixe de clé')),
                ('key_hash', models.CharField(max_length=128, verbose_name='hash de clé')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='dernière utilisation')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expire le')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'clé API',
                'verbose_name_plural': 'clés API',
                'ordering': ['-created_at'],
            },
        ),
    ]
