# Generated by Django 4.2.9 on 2026-01-14 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('credits', models.IntegerField(verbose_name='crédits')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='prix')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='devise')),
                ('stripe_price_id', models.CharField(blank=True, max_length=100, verbose_name='ID prix Stripe')),
                ('is_popular', models.BooleanField(default=False, verbose_name='populaire')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('sort_order', models.IntegerField(default=0, verbose_name='ordre')),
            ],
            options={
                'verbose_name': 'pack de crédits',
                'verbose_name_plural': 'packs de crédits',
                'ordering': ['sort_order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('credit_purchase', 'Achat de crédits'), ('subscription', 'Abonnement'), ('refund', 'Remboursement')], max_length=30, verbose_name='type')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('completed', 'Complété'), ('failed', 'Échoué'), ('refunded', 'Remboursé')], default='pending', max_length=20, verbose_name='statut')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='montant')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='devise')),
                ('credits_purchased', models.IntegerField(default=0, verbose_name='crédits achetés')),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Stripe Payment Intent')),
                ('stripe_checkout_session_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Stripe Checkout Session')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='description')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='métadonnées')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='complété le')),
                ('seller_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='accounts.sellerprofile', verbose_name='profil vendeur')),
            ],
            options={
                'verbose_name': 'transaction de paiement',
                'verbose_name_plural': 'transactions de paiement',
                'ordering': ['-created_at'],
            },
        ),
    ]
