# Generated by Django 4.2.9 on 2026-01-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='payment_method',
            field=models.CharField(choices=[('stripe', 'Carte Bancaire (Stripe)'), ('bank_transfer', 'Virement Bancaire')], default='stripe', max_length=20, verbose_name='méthode de paiement'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='reference_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='référence de commande'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('completed', 'Complété'), ('failed', 'Échoué'), ('refunded', 'Remboursé'), ('cancelled', 'Annulé')], default='pending', max_length=20, verbose_name='statut'),
        ),
    ]
