# Generated by Django 4.2.9 on 2026-01-15 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_paymenttransaction_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment_method',
            field=models.CharField(choices=[('stripe', 'Carte Bancaire (Stripe)'), ('bank_transfer', 'Virement Bancaire')], default='stripe', max_length=20, verbose_name='méthode de paiement'),
        ),
    ]
