# Generated by Django 4.2.9 on 2026-01-14 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_refresh_token_encrypted', models.BinaryField(blank=True, null=True, verbose_name='token de rafraîchissement (chiffré)')),
                ('_access_token_encrypted', models.BinaryField(blank=True, null=True, verbose_name="token d'accès (chiffré)")),
                ('access_token_expires_at', models.DateTimeField(blank=True, null=True, verbose_name="expiration du token d'accès")),
                ('seller_id', models.CharField(blank=True, max_length=50, verbose_name='ID vendeur')),
                ('marketplace_id', models.CharField(blank=True, max_length=50, verbose_name='ID marketplace principal')),
                ('marketplace_ids', models.JSONField(blank=True, default=list, verbose_name='IDs des marketplaces')),
                ('oauth_state', models.CharField(blank=True, max_length=100, null=True, verbose_name='état OAuth')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('last_api_call_at', models.DateTimeField(blank=True, null=True, verbose_name='dernier appel API')),
                ('seller_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='amazon_credentials', to='accounts.sellerprofile', verbose_name='profil vendeur')),
            ],
            options={
                'verbose_name': 'credentials Amazon',
                'verbose_name_plural': 'credentials Amazon',
            },
        ),
        migrations.CreateModel(
            name='ReportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('GET_FBA_MYI_UNSUPPRESSED_INVENTORY_DATA', 'Inventaire FBA'), ('GET_FBA_INVENTORY_AGED_DATA', 'Âge inventaire FBA'), ('GET_FBA_REIMBURSEMENTS_DATA', 'Remboursements FBA'), ('GET_AMAZON_FULFILLED_SHIPMENTS_DATA_GENERAL', 'Expéditions FBA'), ('GET_FBA_FULFILLMENT_CUSTOMER_SHIPMENT_SALES_DATA', 'Ventes expédiées'), ('GET_FBA_FULFILLMENT_CUSTOMER_RETURNS_DATA', 'Retours FBA'), ('GET_FBA_FULFILLMENT_REMOVAL_ORDER_DETAIL_DATA', 'Ordres de retrait'), ('GET_FBA_FULFILLMENT_REMOVAL_SHIPMENT_DETAIL_DATA', 'Expéditions de retrait'), ('GET_FBA_FULFILLMENT_INVENTORY_ADJUSTMENTS_DATA', 'Ajustements inventaire'), ('GET_FBA_STORAGE_FEE_CHARGES_DATA', 'Frais de stockage')], max_length=100, verbose_name='type de rapport')),
                ('marketplace_ids', models.JSONField(default=list, verbose_name='marketplaces')),
                ('report_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='ID de rapport Amazon')),
                ('report_document_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID de document de rapport')),
                ('data_start_date', models.DateField(verbose_name='date de début des données')),
                ('data_end_date', models.DateField(verbose_name='date de fin des données')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('done', 'Terminé'), ('downloaded', 'Téléchargé'), ('failed', 'Échec'), ('cancelled', 'Annulé')], default='pending', max_length=20, verbose_name='statut')),
                ('error_message', models.TextField(blank=True, verbose_name="message d'erreur")),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='chemin du fichier')),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True, verbose_name='taille du fichier (octets)')),
                ('row_count', models.IntegerField(blank=True, null=True, verbose_name='nombre de lignes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='terminé le')),
                ('seller_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_requests', to='accounts.sellerprofile', verbose_name='profil vendeur')),
            ],
            options={
                'verbose_name': 'demande de rapport',
                'verbose_name_plural': 'demandes de rapports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['seller_profile', 'report_type', '-created_at'], name='amazon_inte_seller__e29c47_idx'), models.Index(fields=['status', '-created_at'], name='amazon_inte_status_fd5bbe_idx'), models.Index(fields=['report_id'], name='amazon_inte_report__77742e_idx')],
            },
        ),
        migrations.CreateModel(
            name='APIRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=500, verbose_name='endpoint')),
                ('method', models.CharField(max_length=10, verbose_name='méthode HTTP')),
                ('request_params', models.JSONField(blank=True, default=dict, verbose_name='paramètres')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('success', 'Succès'), ('failed', 'Échec'), ('throttled', 'Rate limited')], default='pending', max_length=20, verbose_name='statut')),
                ('http_status_code', models.IntegerField(blank=True, null=True, verbose_name='code HTTP')),
                ('response_body', models.TextField(blank=True, verbose_name='corps de la réponse')),
                ('error_message', models.TextField(blank=True, verbose_name="message d'erreur")),
                ('request_at', models.DateTimeField(auto_now_add=True, verbose_name='date de la requête')),
                ('response_at', models.DateTimeField(blank=True, null=True, verbose_name='date de la réponse')),
                ('duration_ms', models.IntegerField(blank=True, null=True, verbose_name='durée (ms)')),
                ('retry_count', models.IntegerField(default=0, verbose_name='nombre de tentatives')),
                ('seller_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_request_logs', to='accounts.sellerprofile', verbose_name='profil vendeur')),
            ],
            options={
                'verbose_name': 'log de requête API',
                'verbose_name_plural': 'logs de requêtes API',
                'ordering': ['-request_at'],
                'indexes': [models.Index(fields=['seller_profile', '-request_at'], name='amazon_inte_seller__76451c_idx'), models.Index(fields=['status', '-request_at'], name='amazon_inte_status_136282_idx'), models.Index(fields=['endpoint', '-request_at'], name='amazon_inte_endpoin_38ae18_idx')],
            },
        ),
    ]
