# Generated by Django 4.2.9 on 2026-01-14 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('amazon_integration', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='code de référence')),
                ('start_date', models.DateField(verbose_name='date de début')),
                ('end_date', models.DateField(verbose_name='date de fin')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('fetching', 'Téléchargement des données'), ('processing', 'Traitement en cours'), ('completed', 'Terminé'), ('failed', 'Échec'), ('cancelled', 'Annulé')], default='pending', max_length=20, verbose_name='statut')),
                ('progress_percentage', models.IntegerField(default=0, verbose_name='progression')),
                ('current_step', models.CharField(blank=True, max_length=200, verbose_name='étape en cours')),
                ('error_message', models.TextField(blank=True, verbose_name="message d'erreur")),
                ('celery_task_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID tâche Celery')),
                ('total_items_analyzed', models.IntegerField(default=0, verbose_name='articles analysés')),
                ('total_losses_detected', models.IntegerField(default=0, verbose_name='pertes détectées')),
                ('total_estimated_value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='valeur totale estimée')),
                ('total_already_reimbursed', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='déjà remboursé')),
                ('total_claimable', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='réclamable')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='démarré le')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='terminé le')),
                ('seller_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='accounts.sellerprofile', verbose_name='profil vendeur')),
            ],
            options={
                'verbose_name': 'audit',
                'verbose_name_plural': 'audits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClaimCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='code de référence')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('loss_type', models.CharField(choices=[('lost_inbound', 'Perdu à la réception'), ('lost_warehouse', 'Perdu en entrepôt'), ('damaged_warehouse', 'Endommagé en entrepôt'), ('damaged_inbound', 'Endommagé à la réception'), ('destroyed', 'Détruit par Amazon'), ('return_lost', 'Retour client perdu'), ('return_damaged', 'Retour client endommagé'), ('wrong_reimbursement', 'Remboursement incorrect'), ('no_reimbursement', 'Aucun remboursement'), ('overcharged_fee', 'Frais surtarifés')], max_length=30, verbose_name='type de perte')),
                ('status', models.CharField(choices=[('detected', 'Détecté'), ('pending', 'En attente de révision'), ('ready', 'Prêt à réclamer'), ('claimed', 'Réclamé'), ('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('partial', 'Partiellement remboursé'), ('expired', 'Expiré'), ('duplicate', 'Doublon')], default='detected', max_length=20, verbose_name='statut')),
                ('sku', models.CharField(max_length=100, verbose_name='SKU principal')),
                ('total_quantity', models.IntegerField(verbose_name='quantité totale')),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='valeur totale')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='devise')),
                ('earliest_date', models.DateField(verbose_name='date la plus ancienne')),
                ('latest_date', models.DateField(verbose_name='date la plus récente')),
                ('case_text', models.TextField(blank=True, help_text='Texte pré-généré pour la réclamation', verbose_name='texte de réclamation')),
                ('supporting_data', models.JSONField(blank=True, default=dict, verbose_name='données complémentaires')),
                ('user_notes', models.TextField(blank=True, verbose_name='notes utilisateur')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('claimed_at', models.DateTimeField(blank=True, null=True, verbose_name='réclamé le')),
                ('amazon_case_id', models.CharField(blank=True, max_length=50, verbose_name='ID cas Amazon')),
                ('outcome_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='montant obtenu')),
                ('outcome_notes', models.TextField(blank=True, verbose_name='notes sur le résultat')),
                ('download_count', models.IntegerField(default=0, verbose_name='nombre de téléchargements')),
                ('last_downloaded_at', models.DateTimeField(blank=True, null=True, verbose_name='dernier téléchargement')),
                ('is_paid', models.BooleanField(default=False, help_text='Le dossier a été acheté', verbose_name='payé')),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_cases', to='audit_engine.audit', verbose_name='audit')),
            ],
            options={
                'verbose_name': 'dossier de réclamation',
                'verbose_name_plural': 'dossiers de réclamation',
                'ordering': ['-total_value'],
            },
        ),
        migrations.CreateModel(
            name='AuditReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(max_length=100, verbose_name='type de rapport')),
                ('file_path', models.CharField(max_length=500, verbose_name='chemin du fichier')),
                ('row_count', models.IntegerField(null=True, verbose_name='nombre de lignes')),
                ('is_processed', models.BooleanField(default=False, verbose_name='traité')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='traité le')),
                ('processing_notes', models.TextField(blank=True, verbose_name='notes de traitement')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_reports', to='audit_engine.audit', verbose_name='audit')),
                ('report_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_reports', to='amazon_integration.reportrequest', verbose_name='demande de rapport')),
            ],
            options={
                'verbose_name': "rapport d'audit",
                'verbose_name_plural': "rapports d'audit",
                'ordering': ['audit', 'report_type'],
            },
        ),
        migrations.CreateModel(
            name='LostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=100, verbose_name='SKU')),
                ('fnsku', models.CharField(blank=True, max_length=50, verbose_name='FNSKU')),
                ('asin', models.CharField(blank=True, max_length=20, verbose_name='ASIN')),
                ('product_title', models.CharField(blank=True, max_length=500, verbose_name='titre du produit')),
                ('loss_type', models.CharField(choices=[('lost_inbound', 'Perdu à la réception'), ('lost_warehouse', 'Perdu en entrepôt'), ('damaged_warehouse', 'Endommagé en entrepôt'), ('damaged_inbound', 'Endommagé à la réception'), ('destroyed', 'Détruit par Amazon'), ('return_lost', 'Retour client perdu'), ('return_damaged', 'Retour client endommagé'), ('wrong_reimbursement', 'Remboursement incorrect'), ('no_reimbursement', 'Aucun remboursement'), ('overcharged_fee', 'Frais surtarifés')], max_length=30, verbose_name='type de perte')),
                ('quantity', models.IntegerField(verbose_name='quantité')),
                ('unit_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='valeur unitaire')),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='valeur totale')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='devise')),
                ('transaction_id', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='ID transaction')),
                ('order_id', models.CharField(blank=True, max_length=50, verbose_name='ID commande')),
                ('fulfillment_center', models.CharField(blank=True, max_length=20, verbose_name='centre de distribution')),
                ('reason_code', models.CharField(blank=True, max_length=10, verbose_name='code raison')),
                ('reason_description', models.CharField(blank=True, max_length=200, verbose_name='description raison')),
                ('incident_date', models.DateField(verbose_name="date de l'incident")),
                ('detected_at', models.DateTimeField(auto_now_add=True, verbose_name='détecté le')),
                ('reimbursement_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID remboursement')),
                ('reimbursement_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='montant remboursé')),
                ('is_reimbursed', models.BooleanField(default=False, verbose_name='remboursé')),
                ('unique_hash', models.CharField(db_index=True, help_text='Hash pour éviter les doublons', max_length=64, unique=True, verbose_name='hash unique')),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_items', to='audit_engine.audit', verbose_name='audit')),
                ('claim_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='audit_engine.claimcase', verbose_name='dossier de réclamation')),
            ],
            options={
                'verbose_name': 'article perdu',
                'verbose_name_plural': 'articles perdus',
                'ordering': ['-incident_date'],
                'indexes': [models.Index(fields=['audit', 'loss_type'], name='audit_engin_audit_i_71c955_idx'), models.Index(fields=['sku', '-incident_date'], name='audit_engin_sku_6feaac_idx'), models.Index(fields=['is_reimbursed', '-incident_date'], name='audit_engin_is_reim_7aedc7_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='claimcase',
            index=models.Index(fields=['audit', 'status'], name='audit_engin_audit_i_429454_idx'),
        ),
        migrations.AddIndex(
            model_name='claimcase',
            index=models.Index(fields=['status', '-total_value'], name='audit_engin_status_313548_idx'),
        ),
        migrations.AddIndex(
            model_name='claimcase',
            index=models.Index(fields=['sku', '-created_at'], name='audit_engin_sku_9ad350_idx'),
        ),
        migrations.AddIndex(
            model_name='audit',
            index=models.Index(fields=['seller_profile', '-created_at'], name='audit_engin_seller__c85896_idx'),
        ),
        migrations.AddIndex(
            model_name='audit',
            index=models.Index(fields=['status', '-created_at'], name='audit_engin_status_aa4278_idx'),
        ),
        migrations.AddIndex(
            model_name='audit',
            index=models.Index(fields=['reference_code'], name='audit_engin_referen_267df2_idx'),
        ),
    ]
